{
 "title": "Ping",
 "description": "Ping metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raw",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(probe_success) / count(probe_success)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "DNS Lookup Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds)"
    }
   ]
  },
  {
   "title": "Best Ping Destinations",
   "type": "gauge",
   "gridPos": { "h": 25, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(5, avg_over_time(probe_icmp_duration_seconds{phase=\"rtt\"}[30s]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "15 Second Moving Average",
   "type": "graph",
   "gridPos": { "h": 16, "w": 21, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_icmp_duration_seconds{phase=\"rtt\"}[15s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}