{
 "title": "Starlink Overview",
 "description": "Starlink dish metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Actual Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes / 1000000",
     "legendFormat": "Upload"
    },
    {
     "expr": "starlink_dish_downlink_throughput_bytes /1000000",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Current SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_snr" }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_state" }
   ]
  },
  {
   "title": "24h Obstructed Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_last_24h_obstructed_seconds"
    }
   ]
  },
  {
   "title": "Slow Ethernet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_slow_eth_speeds"
    }
   ]
  },
  {
   "title": "Unexpected Location",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_unexpected_location"
    }
   ]
  },
  {
   "title": "Wedge Fraction Obstructions",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"0\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"1\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"2\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"3\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"4\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"5\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"6\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"7\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"8\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"9\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"10\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"11\"}"
    }
   ]
  },
  {
   "title": "Currently Obstructed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed"
    }
   ]
  },
  {
   "title": "Speed Test",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(speedTest_running)" }
   ]
  },
  {
   "title": "Mast Not Near Vertical",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_mast_not_near_vertical"
    }
   ]
  },
  {
   "title": "Thermal throttle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_throttle"
    }
   ]
  },
  {
   "title": "Latency/Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_latency_seconds",
     "legendFormat": "Latency"
    },
    {
     "expr": "starlink_dish_pop_ping_drop_ratio",
     "legendFormat": "Ping Drop"
    }
   ]
  },
  {
   "title": "Motors Stuck",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_motors_stuck"
    }
   ]
  },
  {
   "title": "Thermal Shutdown",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_shutdown"
    }
   ]
  },
  {
   "title": "Wedge Fraction Obstructions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio * 100 > 0 ",
     "legendFormat": "{{wedge}}"
    }
   ]
  },
  {
   "title": "Seconds To Non-empty Slot",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_first_nonempty_slot_seconds"
    }
   ]
  },
  {
   "title": "Best Speedtest.net In Last 24 Hours",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 15 },
   "options": { "content": "\n         " }
  },
  {
   "title": "SNR",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "SNR" }
   ],
   "targets": [
    { "expr": "starlink_dish_snr", "legendFormat": "SNR" },
    {
     "expr": "starlink_dish_currently_obstructed",
     "legendFormat": "Obstructed"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedTest_download_speed_Bps[1d:5m]))"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedTest_upload_speed_Bps[1d:5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedTest_latency_seconds[1d:5m]))"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{ job }}" }
   ]
  }
 ]
}